//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISevice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecanico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mecanico()
        {
            this.Servicio = new HashSet<Servicio>();
            this.Factura = new HashSet<Factura>();
        }
    
        public int IDMECANICO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string EVALUACION_DAÑOS { get; set; }
        public string TIEMPO_REPARACION { get; set; }
        public decimal MANO_DE_OBRA { get; set; }
        public int IDVEHICULO { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
