//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISevice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Repuesto()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int IDREPUESTO { get; set; }
        public string NOMBRE { get; set; }
        public decimal PRECIO { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public int IDVEHICULO { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
